exports.bug = ["Accelgor", "Araquanid", "Ariados", "Armaldo", "Beautifly", "Beedrill", "Butterfree", "Buzzwole", "Durant", "Dustox", "Escavalier", "Forretress", "Galvantula", "Golisopod", "Heracross", "Illumise", "Kricketune", "Leavanny", "Ledian", "Masquerain", "Mothim", "Ninjask", "Parasect", "Pinsir", "Ribombee", "Scizor", "Scolipede", "Scyther", "Shedinja", "Shuckle", "Silvally-Bug", "Venomoth", "Vespiquen", "Vikavolt", "Vivillon", "Volbeat", "Volcarona", "Wormadam", "Yanmega"];

exports.dark = ["Absol", "Bisharp", "Cacturne", "Crawdaunt", "Drapion", "Greninja", "Guzzlord", "Honchkrow", "Hoopa-Unbound", "Houndoom", "Hydreigon", "Incineroar", "Krookodile", "Liepard", "Malamar", "Mandibuzz", "Mightyena", "Muk-Alola", "Pangoro", "Persian-Alola", "Raticate-Alola", "Raticate-Alola-Totem", "Sableye", "Scrafty", "Sharpedo", "Shiftry", "Silvally-Dark", "Skuntank", "Sneasel", "Spiritomb", "Tyranitar", "Umbreon", "Weavile", "Zoroark"];

exports.dragon = ["Altaria", "Ampharos-Mega", "Charizard-Mega-X", "Dragalge", "Drampa", "Druddigon", "Exeggutor-Alola", "Flygon", "Garchomp", "Goodra", "Guzzlord", "Haxorus", "Hydreigon", "Kingdra", "Kommo-o", "Latias", "Latios", "Noivern", "Salamence", "Sceptile-Mega", "Silvally-Dragon", "Turtonator", "Tyrantrum", "Zygarde-10%"];

exports.electric = ["Ampharos", "Dedenne", "Eelektross", "Electivire", "Electrode", "Emolga", "Galvantula", "Golem-Alola", "Heliolisk", "Jolteon", "Lanturn", "Luxray", "Magneton", "Magnezone", "Manectric", "Minun", "Oricorio-Pom-Pom", "Pachirisu", "Pikachu-Alola", "Pikachu-Hoenn", "Pikachu-Kalos", "Pikachu-Original", "Pikachu-Partner", "Pikachu-Sinnoh", "Pikachu-Unova", "Plusle", "Raichu", "Raichu-Alola", "Raikou", "Rotom", "Silvally-Electric", "Stunfisk", "Thundurus", "Togedemaru", "Vikavolt", "Xurkitree", "Zapdos", "Zebstrika", "Zeraora"];

exports.fairy = ["Altaria-Mega", "Aromatisse", "Audino-Mega", "Azumarill", "Carbink", "Clefable", "Clefairy", "Comfey", "Dedenne", "Diancie", "Florges", "Gardevoir", "Granbull", "Klefki", "Mawile", "Mr. Mime", "Ninetales-Alola", "Primarina", "Ribombee", "Shiinotic", "Silvally-Fairy", "Slurpuff", "Sylveon", "Tapu Bulu", "Tapu Fini", "Tapu Lele", "Togekiss", "Whimsicott", "Wigglytuff"];

exports.fighting = ["Bewear", "Breloom", "Buzzwole", "Chesnaught", "Cobalion", "Conkeldurr", "Crabominable", "Emboar", "Gallade", "Gurdurr", "Hariyama", "Heracross", "Hitmonchan", "Hitmonlee", "Hitmontop", "Infernape", "Keldeo", "Kommo-o", "Lopunny-Mega", "Lucario", "Machamp", "Medicham", "Mienshao", "Pangoro", "Passimian", "Poliwrath", "Primeape", "Sawk", "Scrafty", "Silvally-Fighting", "Terrakion", "Throh", "Toxicroak", "Virizion"];

exports.fire = ["Arcanine", "Blacephalon", "Camerupt", "Castform-Sunny", "Chandelure", "Charizard", "Darmanitan", "Delphox", "Emboar", "Entei", "Flareon", "Heatmor", "Heatran", "Houndoom", "Incineroar", "Infernape", "Magcargo", "Magmortar", "Marowak-Alola", "Marowak-Alola-Totem", "Moltres", "Ninetales", "Oricorio", "Pyroar", "Rapidash", "Rotom-Heat", "Salazzle", "Silvally-Fire", "Simisear", "Talonflame", "Torkoal", "Turtonator", "Typhlosion", "Victini", "Volcarona"];

exports.flying = ["Aerodactyl", "Altaria", "Archeops", "Articuno", "Beautifly", "Braviary", "Butterfree", "Celesteela", "Charizard", "Chatot", "Crobat", "Delibird", "Dodrio", "Drifblim", "Emolga", "Farfetch'd", "Fearow", "Gligar", "Gliscor", "Golbat", "Gyarados", "Hawlucha", "Honchkrow", "Jumpluff", "Landorus-Therian", "Ledian", "Mandibuzz", "Mantine", "Masquerain", "Minior", "Moltres", "Mothim", "Ninjask", "Noctowl", "Noivern", "Oricorio", "Pelipper", "Pidgeot", "Pinsir-Mega", "Rotom-Fan", "Salamence", "Scyther", "Sigilyph", "Silvally-Flying", "Skarmory", "Staraptor", "Swanna", "Swellow", "Swoobat", "Talonflame", "Thundurus", "Togekiss", "Tornadus", "Toucannon", "Tropius", "Unfezant", "Vespiquen", "Vivillon", "Xatu", "Yanmega", "Zapdos"];

exports.ghost = ["Banette", "Blacephalon", "Chandelure", "Cofagrigus", "Decidueye", "Dhelmise", "Doublade", "Drifblim", "Dusknoir", "Froslass", "Gengar", "Golurk", "Gourgeist", "Haunter", "Hoopa", "Jellicent", "Marowak-Alola", "Marowak-Alola-Totem", "Mismagius", "Oricorio-Sensu", "Palossand", "Rotom", "Sableye", "Shedinja", "Silvally-Ghost", "Spiritomb", "Trevenant"];

exports.grass = ["Abomasnow", "Amoonguss", "Bellossom", "Breloom", "Cacturne", "Carnivine", "Celebi", "Cherrim", "Chesnaught", "Cradily", "Decidueye", "Dhelmise", "Exeggutor", "Exeggutor-Alola", "Ferroseed", "Ferrothorn", "Gogoat", "Jumpluff", "Kartana", "Leafeon", "Leavanny", "Lilligant", "Ludicolo", "Lurantis", "Maractus", "Meganium", "Parasect", "Roselia", "Roserade", "Rotom-Mow", "Sawsbuck", "Sceptile", "Serperior", "Shaymin", "Shiftry", "Shiinotic", "Silvally-Grass", "Simisage", "Sunflora", "Tangrowth", "Tapu Bulu", "Torterra", "Trevenant", "Tropius", "Tsareena", "Venusaur", "Victreebel", "Vileplume", "Virizion", "Whimsicott", "Wormadam"];

exports.ground = ["Camerupt", "Claydol", "Diggersby", "Donphan", "Dugtrio", "Dugtrio-Alola", "Excadrill", "Flygon", "Garchomp", "Gastrodon", "Gligar", "Gliscor", "Golem", "Golurk", "Hippowdon", "Krookodile", "Landorus-Therian", "Mamoswine", "Marowak", "Mudsdale", "Nidoking", "Nidoqueen", "Palossand", "Piloswine", "Quagsire", "Rhydon", "Rhyperior", "Sandslash", "Seismitoad", "Silvally-Ground", "Steelix", "Stunfisk", "Swampert", "Torterra", "Whiscash", "Wormadam-Sandy", "Zygarde-10%"];

exports.ice = ["Abomasnow", "Articuno", "Aurorus", "Avalugg", "Beartic", "Castform-Snowy", "Cloyster", "Crabominable", "Cryogonal", "Delibird", "Dewgong", "Froslass", "Glaceon", "Glalie", "Jynx", "Lapras", "Mamoswine", "Ninetales-Alola", "Piloswine", "Regice", "Rotom-Frost", "Sandslash-Alola", "Silvally-Ice", "Sneasel", "Vanilluxe", "Walrein", "Weavile"];

exports.normal = ["Ambipom", "Audino", "Bewear", "Bibarel", "Blissey", "Bouffalant", "Braviary", "Castform", "Chansey", "Chatot", "Cinccino", "Delcatty", "Diggersby", "Ditto", "Dodrio", "Drampa", "Dunsparce", "Exploud", "Farfetch'd", "Fearow", "Furfrou", "Furret", "Girafarig", "Gumshoos", "Heliolisk", "Kangaskhan", "Kecleon", "Komala", "Lickilicky", "Linoone", "Lopunny", "Miltank", "Noctowl", "Oranguru", "Persian", "Pidgeot", "Porygon-Z", "Porygon2", "Purugly", "Pyroar", "Raticate", "Raticate-Alola", "Regigigas", "Sawsbuck", "Silvally", "Slaking", "Smeargle", "Spinda", "Stantler", "Staraptor", "Stoutland", "Swellow", "Tauros", "Toucannon", "Type: Null", "Unfezant", "Ursaring", "Watchog", "Wigglytuff", "Zangoose"];

exports.poison = ["Amoonguss", "Arbok", "Ariados", "Beedrill", "Crobat", "Dragalge", "Drapion", "Dustox", "Garbodor", "Gengar", "Golbat", "Haunter", "Muk", "Muk-Alola", "Nidoking", "Nidoqueen", "Nihilego", "Qwilfish", "Roselia", "Roserade", "Salazzle", "Scolipede", "Seviper", "Silvally-Poison", "Skuntank", "Swalot", "Tentacruel", "Toxapex", "Toxicroak", "Venomoth", "Venusaur", "Victreebel", "Vileplume", "Weezing"];

exports.psychic = ["Alakazam", "Azelf", "Beheeyem", "Bronzong", "Bruxish", "Celebi", "Chimecho", "Claydol", "Cresselia", "Darmanitan-Zen", "Delphox", "Espeon", "Exeggutor", "Gallade", "Gardevoir", "Girafarig", "Gothitelle", "Grumpig", "Hoopa", "Hypno", "Jynx", "Latias", "Latios", "Lunatone", "Malamar", "Medicham", "Meloetta", "Meowstic", "Mesprit", "Metagross", "Mew", "Mr. Mime", "Musharna", "Necrozma", "Oranguru", "Oricorio-Pa'u", "Raichu-Alola", "Reuniclus", "Sigilyph", "Silvally-Psychic", "Slowbro", "Slowking", "Solrock", "Starmie", "Swoobat", "Tapu Lele", "Unown", "Uxie", "Victini", "Wobbuffet", "Xatu"];

exports.rock = ["Aerodactyl", "Aggron", "Archeops", "Armaldo", "Aurorus", "Barbaracle", "Bastiodon", "Carbink", "Carracosta", "Corsola", "Cradily", "Crustle", "Diancie", "Gigalith", "Golem", "Golem-Alola", "Kabutops", "Lunatone", "Lycanroc", "Magcargo", "Minior", "Nihilego", "Omastar", "Probopass", "Rampardos", "Regirock", "Relicanth", "Rhydon", "Rhyperior", "Shuckle", "Silvally-Rock", "Solrock", "Stakataka", "Sudowoodo", "Terrakion", "Tyranitar", "Tyrantrum"];

exports.steel = ["Aggron", "Bastiodon", "Bisharp", "Bronzong", "Celesteela", "Cobalion", "Doublade", "Dugtrio-Alola", "Durant", "Empoleon", "Escavalier", "Excadrill", "Ferroseed", "Ferrothorn", "Forretress", "Heatran", "Kartana", "Klefki", "Klinklang", "Lucario", "Magearna", "Magneton", "Magnezone", "Mawile", "Metagross", "Probopass", "Registeel", "Sandslash-Alola", "Scizor", "Silvally-Steel", "Skarmory", "Stakataka", "Steelix", "Togedemaru", "Wormadam-Trash"];

exports.water = ["Alomomola", "Araquanid", "Azumarill", "Barbaracle", "Basculin", "Bibarel", "Blastoise", "Bruxish", "Carracosta", "Castform-Rainy", "Clawitzer", "Cloyster", "Corsola", "Crawdaunt", "Dewgong", "Empoleon", "Feraligatr", "Floatzel", "Gastrodon", "Golduck", "Golisopod", "Gorebyss", "Greninja", "Gyarados", "Huntail", "Jellicent", "Kabutops", "Keldeo", "Kingdra", "Kingler", "Lanturn", "Lapras", "Ludicolo", "Lumineon", "Luvdisc", "Manaphy", "Mantine", "Milotic", "Octillery", "Omastar", "Pelipper", "Phione", "Politoed", "Poliwrath", "Primarina", "Pyukumuku", "Quagsire", "Qwilfish", "Relicanth", "Samurott", "Seaking", "Seismitoad", "Sharpedo", "Silvally-Water", "Simipour", "Slowbro", "Slowking", "Starmie", "Suicune", "Swampert", "Swanna", "Tapu Fini", "Tentacruel", "Toxapex", "Vaporeon", "Volcanion", "Wailord", "Walrein", "Whiscash", "Wishiwashi"];