exports.grass = '/tour name Type Challenge: Grass!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Wormadam-Sandy, -Wormadam-Trash, -Gourgeist, +Abomasnow, +Abomasnow-Mega, +Amoonguss, +Bayleef, +Bellossom, +Bellsprout, +Bounsweet, +Breloom, +Budew, +Bulbasaur, +Cacnea, +Cacturne, +Carnivine, +Celebi, +Cherrim, +Cherubi, +Chesnaught, +Chespin, +Chikorita, +Cottonee, +Cradily, +Dartrix, +Decidueye, +Deerling, +Dhelmise, +Exeggcute, +Exeggutor, +Ferroseed, +Ferrothorn, +Fomantis, +Foongus, +Gloom, +Gogoat, +Grotle, +Grovyle, +Hoppip, +Ivysaur, +Jumpluff, +Kartana, +Leafeon, +Leavanny, +Lileep, +Lilligant, +Lombre, +Lotad, +Ludicolo, +Lurantis, +Lurantis-Totem, +Maractus, +Meganium, +Morelull, +Nuzleaf, +Oddish, +Pansage, +Paras, +Parasect, +Petilil, +Phantump, +Pumpkaboo, +Quilladin, +Roselia, +Roserade, +Rotom-Mow, +Rowlet, +Sawsbuck, +Sceptile, +Sceptile-Mega, +Seedot, +Serperior, +Servine, +Sewaddle, +Shaymin, +Shiftry, +Shiinotic, +Shroomish, +Silvally-Grass, +Simisage, +Skiddo, +Skiploom, +Snivy, +Snover, +Steenee, +Sunflora, +Sunkern, +Swadloon, +Tangela, +Tangrowth, +Tapu Bulu, +Torterra, +Treecko, +Trevenant, +Tropius, +Tsareena, +Turtwig, +Venusaur, +Venusaur-Mega, +Victreebel, +Vileplume, +Virizion, +Weepinbell, +Whimsicott, +Wormadam\n/wall Type Challenge: Grass!';



exports.fire = '/tour name Type Challenge: Fire!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Ninetales-Alola, -Vulpix-Alola, -Cameruptite, -Volcanion, +Arcanine, +Blacephalon, +Blaziken, +Blaziken-Mega, +Braixen, +Camerupt, +Chandelure, +Charizard, +Charizard-Mega-X, +Charizard-Mega-Y, +Charmander, +Charmeleon, +Chimchar, +Combusken, +Cyndaquil, +Darmanitan, +Darumaka, +Delphox, +Emboar, +Entei, +Fennekin, +Flareon, +Fletchinder, +Growlithe, +Heatmor, +Heatran, +Houndoom, +Houndoom-Mega, +Houndour, +Incineroar, +Infernape, +Lampent, +Larvesta, +Litleo, +Litten, +Litwick, +Magby, +Magcargo, +Magmar, +Magmortar, +Marowak-Alola, +Moltres, +Monferno, +Ninetales, +Numel, +Oricorio, +Pansear, +Pignite, +Ponyta, +Pyroar, +Quilava, +Rapidash, +Rotom-Heat, +Salandit, +Salazzle, +Silvally-Fire, +Simisear, +Slugma, +Talonflame, +Tepig, +Torchic, +Torkoal, +Torracat, +Turtonator, +Typhlosion, +Victini, +Volcarona, +Vulpix\n/wall Type Challenge: Fire!';



exports.bug = '/tour name Type Challenge: Bug!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Crustle, -Genesect, +Accelgor, +Anorith, +Araquanid, +Ariados, +Armaldo, +Beautifly, +Beedrill, +Beedrill-Mega, +Burmy, +Butterfree, +Buzzwole, +Cascoon, +Caterpie, +Charjabug, +Combee, +Cutiefly, +Dewpider, +Durant, +Dustox, +Dwebble, +Escavalier, +Forretress, +Galvantula, +Golisopod, +Grubbin, +Heracross, +Heracross-Mega, +Illumise, +Joltik, +Kakuna, +Karrablast, +Kricketot, +Kricketune, +Larvesta, +Leavanny, +Ledian, +Ledyba, +Masquerain, +Metapod, +Mothim, +Nincada, +Ninjask, +Paras, +Parasect, +Pheromosa, +Pineco, +Pinsir, +Pinsir-Mega, +Ribombee, +Scatterbug, +Scizor, +Scizor-Mega, +Scolipede, +Scyther, +Sewaddle, +Shedinja, +Shelmet, +Shuckle, +Silcoon, +Silvally-Bug, +Skorupi, +Spewpa, +Spinarak, +Surskit, +Swadloon, +Venipede, +Venomoth, +Venonat, +Vespiquen, +Vikavolt, +Vivillon, +Volbeat, +Volcarona, +Weedle, +Whirlipede, +Wimpod, +Wormadam, +Wurmple, +Yanma, +Yanmega\n/wall Type Challenge: Bug!';



exports.dark = '/tour name Type Challenge: Dark!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, +Absol, +Absol-Mega, +Bisharp, +Cacturne, +Carvanha, +Crawdaunt, +Deino, +Drapion, +Greninja, +Grimer-Alola, +Guzzlord, +Honchkrow, +Hoopa-Unbound, +Houndoom, +Houndoom-Mega, +Houndour, +Hydreigon, +Incineroar, +Inkay, +Krokorok, +Krookodile, +Liepard, +Malamar, +Mandibuzz, +Meowth-Alola, +Mightyena, +Muk-Alola, +Murkrow, +Nuzleaf, +Pangoro, +Pawniard, +Persian-Alola, +Poochyena, +Purrloin, +Raticate-Alola, +Rattata-Alola, +Sableye, +Sableye-Mega, +Sandile, +Scrafty, +Scraggy, +Sharpedo, +Sharpedo-Mega, +Shiftry, +Silvally-Dark, +Skuntank, +Sneasel, +Spiritomb, +Stunky, +Tyranitar, +Tyranitar-Mega, +Umbreon, +Vullaby, +Weavile, +Zoroark, +Zorua, +Zweilous\n/wall Type Challenge: Dark!';



exports.dragon = '/tour name Type Challenge: Dragon!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Exeggutor, -Altarianite, -Dragonite, -Kyurem, +Altaria, +Axew, +Bagon, +Deino, +Dragalge, +Dragonair, +Drampa, +Dratini, +Druddigon, +Exeggutor-Alola, +Flygon, +Fraxure, +Gabite, +Garchomp, +Garchomp-Mega, +Gible, +Goodra, +Goomy, +Guzzlord, +Hakamo-o, +Haxorus, +Hydreigon, +Jangmo-o, +Kingdra, +Kommo-o, +Latias, +Latias-Mega, +Latios, +Latios-Mega, +Naganadel, +Noibat, +Noivern, +Salamence, +Shelgon, +Silvally-Dragon, +Sliggoo, +Turtonator, +Tyrantrum, +Tyrunt, +Vibrava, +Zweilous, +Zygarde\n/wall Type Challenge: Dragon!';



exports.electric = '/tour name Type Challenge: Electric!\n/tour rules -OU, -PU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Lucarionite, -Gengarite, -Blaziken, -Blazikenite, -Deoxys-Speed, -Landorus-Incarnate, -Aegislash, -Genesect, -Pheromosa, -Naganadel, -Metagrossite, -UUBL, -NUBL, -PUBL, -RUBL, -NFE, -LC Uber, -Zygarde, -Geodude, -Golem, -Graveler, +Ampharos, +Ampharos-Mega, +Blitzle, +Charjabug, +Chinchou, +Dedenne, +Eelektrik, +Eelektross, +Electabuzz, +Electivire, +Electrike, +Electrode, +Elekid, +Emolga, +Flaaffy, +Galvantula, +Geodude-Alola, +Golem-Alola, +Graveler-Alola, +Heliolisk, +Helioptile, +Jolteon, +Joltik, +Lanturn, +Luxio, +Luxray, +Magnemite, +Magneton, +Magnezone, +Manectric, +Manectric-Mega, +Mareep, +Minun, +Oricorio-Pom-Pom, +Pachirisu, +Pichu, +Pikachu, +Plusle, +Raichu, +Raikou, +Rotom, +Shinx, +Silvally-Electric, +Stunfisk, +Thundurus, +Togedemaru, +Tynamo, +Vikavolt, +Voltorb, +Xurkitree, +Zapdos, +Zebstrika, +Zeraora\n/wall Type Challenge: Electric!';



exports.fairy = '/tour name Type Challenge: Fairy!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Magearna, +Aromatisse, +Azumarill, +Azurill, +Carbink, +Clefable, +Clefairy, +Cleffa, +Comfey, +Cottonee, +Cutiefly, +Dedenne, +Diancie, +Diancie-Mega, +FlabeÂ´beÂ´, +Floette, +Florges, +Gardevoir, +Gardevoir-Mega, +Granbull, +Igglybuff, +Jigglypuff, +Kirlia, +Klefki, +Marill, +Mawile, +Mawile-Mega, +Mime Jr., +Morelull, +Mr. Mime, +Ninetales-Alola, +Primarina, +Ralts, +Ribombee, +Shiinotic, +Silvally-Fairy, +Slurpuff, +Snubbull, +Spritzee, +Swirlix, +Sylveon, +Tapu Bulu, +Tapu Fini, +Tapu Lele, +Togekiss, +Togepi, +Togetic, +Whimsicott, +Wigglytuff\n/wall Type Challenge: Fairy!';



exports.fighting = '/tour name Type Challenge: Fighting!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Galladite, -Hawlucha, -Kommonium-Z, +Bewear, +Blaziken, +Blaziken-Mega, +Breloom, +Buzzwole, +Chesnaught, +Cobalion, +Combusken, +Conkeldurr, +Crabominable, +Crabrawler, +Croagunk, +Emboar, +Gallade, +Gurdurr, +Hakamo-o, +Hariyama, +Heracross, +Heracross-Mega, +Hitmonchan, +Hitmonlee, +Hitmontop, +Infernape, +Keldeo, +Kommo-o, +Lucario, +Lucario-Mega, +Machamp, +Machoke, +Machop, +Makuhita, +Mankey, +Medicham, +Medicham-Mega, +Meditite,  +Mienfoo, +Mienshao, +Monferno, +Pancham, +Pangoro, +Passimian, +Pheromosa, +Pignite, +Poliwrath, +Primeape, +Riolu, +Sawk, +Scrafty, +Scraggy, +Silvally-Fighting, +Stufful, +Terrakion, +Throh, +Timburr, +Toxicroak, +Tyrogue, +Virizion\n/wall Type Challenge: Fighting!';



exports.flying = "/tour name Type Challenge: Flying!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, +Aerodactyl, +Aerodactyl-Mega, +Altaria, +Archen, +Archeops, +Articuno, +Beautifly, +Braviary, +Butterfree, +Celesteela, +Charizard, +Charizard-Mega-Y, +Chatot, +Combee, +Crobat, +Dartrix, +Delibird, +Dodrio, +Doduo, +Drifblim, +Drifloon, +Ducklett, +Emolga, +Farfetch'd, +Fearow, +Fletchinder, +Fletchling, +Gligar, +Gliscor, +Golbat, +Gyarados, +Hawlucha, +Honchkrow, +Hoothoot, +Hoppip, +Jumpluff, +Landorus, +Ledian, +Ledyba, +Mandibuzz, +Mantine, +Mantyke, +Masquerain, +Minior, +Moltres, +Mothim, +Murkrow, +Natu, +Ninjask, +Noctowl, +Noibat, +Noivern, +Oricorio, +Pelipper, +Pidgeot, +Pidgeot-Mega, +Pidgeotto, +Pidgey, +Pidove, +Pikipek, +Rotom-Fan, +Rowlet, +Rufflet, +Salamence, +Scyther, +Sigilyph, +Silvally-Flying, +Skarmory, +Skiploom, +Spearow, +Staraptor, +Staravia, +Starly, +Swablu, +Swanna, +Swellow, +Swoobat, +Taillow, +Talonflame, +Thundurus, +Togekiss, +Togetic, +Tornadus, +Toucannon, +Tranquill, +Tropius, +Trumbeak, +Unfezant, +Vespiquen, +Vivillon, +Vullaby, +Wingull, +Woobat, +Xatu, +Yanma, +Yanmega, +Zapdos, +Zubat\n/wall Type Challenge: Flying!";


exports.ghost = '/tour name Type Challenge: Ghost!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Hoopa-Unbound, -Sablenite, +Aegislash, +Banette, +Banette-Mega, +Blacephalon, +Chandelure, +Cofagrigus, +Decidueye, +Dhelmise, +Doublade, +Drifblim, +Drifloon, +Dusclops, +Dusknoir, +Duskull, +Frillish, +Froslass, +Gastly, +Gengar, +Gengar-Mega, +Golett, +Golurk, +Gourgeist, +Haunter, +Honedge, +Hoopa, +Jellicent, +Lampent, +Litwick, +Marowak-Alola, +Misdreavus, +Mismagius, +Oricorio-Sensu, +Palossand, +Phantump, +Pumpkaboo, +Rotom, +Sableye, +Sandygast, +Shedinja, +Shuppet, +Silvally-Ghost, +Spiritomb, +Trevenant, +Yamask\n/wall Type Challenge: Ghost!';



exports.ground = '/tour name Type Challenge: Ground!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Geodude-Alola, -Graveler-Alola, -Golem-Alola, -Marowak-Alola, -Sandshrew-Alola, -Sandslash-Alola, +Baltoy, +Barboach, +Camerupt, +Camerupt-Mega, +Claydol, +Cubone, +Diggersby, +Diglett, +Donphan, +Drilbur, +Dugtrio, +Excadrill, +Flygon, +Gabite, +Garchomp, +Garchomp-Mega, +Gastrodon, +Geodude, +Gible, +Gligar, +Gliscor, +Golem, +Golett, +Golurk, +Graveler, +Hippopotas, +Hippowdon, +Krokorok, +Krookodile, +Landorus, +Larvitar, +Mamoswine, +Marowak, +Marshtomp, +Mudbray, +Mudsdale, +Nidoking, +Nidoqueen, +Nincada, +Numel, +Onix, +Palossand, +Palpitoad, +Phanpy, +Piloswine, +Pupitar, +Quagsire, +Rhydon, +Rhyhorn, +Rhyperior, +Sandile, +Sandshrew, +Sandslash, +Sandygast, +Seismitoad, +Silvally-Ground, +Steelix, +Steelix-Mega, +Stunfisk, +Swampert, +Swampert-Mega, +Swinub, +Torterra, +Trapinch, +Vibrava, +Whiscash, +Wooper, +Wormadam-Sandy, +Zygarde\n/wall Type Challenge: Ground!';



exports.ice = '/tour name Type Challenge: Ice!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Kyurem, +Abomasnow, +Abomasnow-Mega, +Amaura, +Articuno, +Aurorus, +Avalugg, +Beartic, +Bergmite, +Cloyster, +Crabominable, +Cryogonal, +Cubchoo, +Delibird, +Dewgong, +Froslass, +Glaceon, +Glalie, +Glalie-Mega, +Jynx, +Lapras, +Mamoswine, +Ninetales-Alola, +Piloswine, +Regice, +Rotom-Frost, +Sandshrew-Alola, +Sandslash-Alola, +Sealeo, +Silvally-Ice, +Smoochum, +Sneasel, +Snorunt, +Snover, +Spheal, +Swinub, +Vanillish, +Vanillite, +Vanilluxe, +Vulpix-Alola, +Walrein, +Weavile\n/wall Type Challenge: Ice!';



exports.normal = "/tour name Type Challenge: Normal!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Meowth-Alola, -Persian-Alola, -Meloetta, +Aipom, +Ambipom, +Audino, +Audino-Mega, +Azurill, +Bewear, +Bibarel, +Bidoof, +Blissey, +Bouffalant, +Braviary, +Buneary, +Bunnelby, +Castform, +Chansey, +Chatot, +Cinccino, +Deerling, +Delcatty, +Diggersby, +Ditto, +Dodrio, +Doduo, +Drampa, +Dunsparce, +Eevee, +Exploud, +Farfetch'd, +Fearow, +Fletchling, +Furfrou, +Furret, +Girafarig, +Glameow, +Gumshoos, +Happiny, +Heliolisk, +Helioptile, +Herdier, +Hoothoot, +Igglybuff, +Jigglypuff, +Kangaskhan, +Kecleon, +Komala, +Lickilicky, +Lickitung, +Lillipup, +Linoone, +Litleo, +Lopunny, +Lopunny-Mega, +Loudred, +Meowth, +Miltank, +Minccino, +Munchlax, +Noctowl, +Oranguru, +Patrat, +Persian, +Pidgeot, +Pidgeot-Mega, +Pidgeotto, +Pidgey, +Pidove, +Pikipek, +Porygon, +Porygon-Z, +Porygon2, +Purugly, +Pyroar, +Raticate, +Rattata, +Regigigas, +Rufflet, +Sawsbuck, +Sentret, +Silvally, +Skitty, +Slaking, +Slakoth, +Smeargle, +Spearow, +Spinda, +Stantler, +Staraptor, +Staravia, +Starly, +Stoutland, +Stufful, +Swablu, +Swellow, +Taillow, +Tauros, +Teddiursa, +Toucannon, +Tranquill, +Trumbeak, +Type: Null, +Unfezant, +Ursaring, +Vigoroth, +Watchog, +Whismur, +Wigglytuff, +Yungoos, +Zangoose, +Zigzagoon\n/wall Type Challenge: Normal!";



exports.poison = '/tour name Type Challenge: Poison!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Naganadel, +Amoonguss, +Arbok, +Ariados, +Beedrill, +Beedrill-Mega, +Bellsprout, +Budew, +Bulbasaur, +Croagunk, +Crobat, +Dragalge, +Drapion, +Dustox, +Ekans, +Foongus, +Garbodor, +Gastly, +Gengar, +Gengar-Mega, +Gloom, +Golbat, +Grimer, +Gulpin, +Haunter, +Ivysaur, +Kakuna, +Koffing, +Mareanie, +Muk, +Nidoking, +Nidoqueen, +Nidoran-F, +Nidoran-M, +Nidorina, +Nidorino, +Nihilego, +Oddish, +Poipole, +Qwilfish, +Roselia, +Roserade, +Salandit, +Salazzle, +Scolipede, +Seviper, +Silvally-Poison, +Skorupi, +Skrelp, +Skuntank, +Spinarak, +Stunky, +Swalot, +Tentacool, +Tentacruel, +Toxapex, +Toxicroak, +Trubbish, +Venipede, +Venomoth, +Venonat, +Venusaur, +Venusaur-Mega, +Victreebel, +Vileplume, +Weedle, +Weepinbell, +Weezing, +Whirlipede, +Zubat\n/wall Type Challenge: Poison!';



exports.psychic = "/tour name Type Challenge: Psychic!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Relic Song, -Exeggutor-Alola, +Abra, +Alakazam, +Alakazam-Mega, +Azelf, +Baltoy, +Beheeyem, +Beldum, +Bronzong, +Bronzor, +Bruxish, +Celebi, +Chimecho, +Chingling, +Claydol, +Cosmoem, +Cosmog, +Cresselia, +Delphox, +Deoxys-Speed, +Drowzee, +Duosion, +Elgyem, +Espeon, +Espurr, +Exeggcute, +Exeggutor, +Gallade, +Gallade-Mega, +Gardevoir, +Gardevoir-Mega, +Girafarig, +Gothita, +Gothitelle, +Gothorita, +Grumpig, +Hoopa, +Hypno, +Inkay, +Jynx, +Kadabra, +Kirlia, +Latias, +Latias-Mega, +Latios, +Latios-Mega, +Lunatone, +Malamar, +Medicham, +Medicham-Mega, +Meditite, +Meloetta, +Meowstic, +Mesprit, +Metagross, +Metagross-Mega, +Metang, +Mew, +Mime Jr., +Mr. Mime, +Munna, +Musharna, +Natu, +Necrozma, +Oranguru, +Oricorio-Pa'u, +Raichu-Alola, +Ralts, +Reuniclus, +Sigilyph, +Silvally-Psychic, +Slowbro, +Slowbro-Mega, +Slowking, +Slowpoke, +Smoochum, +Solosis, +Solrock, +Spoink, +Starmie, +Swoobat, +Tapu Lele, +Unown, +Uxie, +Victini, +Wobbuffet, +Woobat, +Wynaut, +Xatu\n/wall Type Challenge: Psychic!";



exports.rock = '/tour name Type Challenge: Rock!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Relicanth, +Aerodactyl, +Aerodactyl-Mega, +Aggron, +Amaura, +Anorith, +Archen, +Archeops, +Armaldo, +Aron, +Aurorus, +Barbaracle, +Bastiodon, +Binacle, +Boldore, +Bonsly, +Carbink, +Carracosta, +Corsola, +Cradily, +Cranidos, +Crustle, +Diancie, +Diancie-Mega, +Dwebble, +Geodude, +Gigalith, +Golem, +Graveler, +Kabuto, +Kabutops, +Lairon, +Larvitar, +Lileep, +Lunatone, +Lycanroc, +Magcargo, +Minior, +Nihilego, +Nosepass, +Omanyte, +Omastar, +Onix, +Probopass, +Pupitar, +Rampardos, +Regirock, +Rhydon, +Rhyhorn, +Rhyperior, +Rockruff, +Roggenrola, +Shieldon, +Shuckle, +Silvally-Rock, +Solrock, +Stakataka, +Sudowoodo, +Terrakion, +Tirtouga, +Tyranitar, +Tyranitar-Mega, +Tyrantrum, +Tyrunt\n/wall Type Challenge: Rock!';



exports.steel = '/tour name Type Challenge: Steel!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, +Aegislash, +Aggron, +Aggron-Mega, +Aron, +Bastiodon, +Beldum, +Bisharp, +Bronzong, +Bronzor, +Celesteela, +Cobalion, +Diglett-Alola, +Doublade, +Dugtrio-Alola, +Durant, +Empoleon, +Escavalier, +Excadrill, +Ferroseed, +Ferrothorn, +Forretress, +Genesect, +Heatran, +Honedge, +Kartana, +Klang, +Klefki, +Klink, +Klinklang, +Lairon, +Lucario, +Lucario-Mega, +Magearna, +Magnemite, +Magneton, +Magnezone, +Mawile, +Mawile-Mega, +Metagross, +Metagross-Mega, +Metang, +Pawniard, +Probopass, +Registeel, +Sandshrew-Alola, +Sandslash-Alola, +Scizor, +Scizor-Mega, +Shieldon, +Silvally-Steel, +Skarmory, +Stakataka, +Steelix, +Steelix-Mega, +Togedemaru, +Wormadam-Trash\n/wall Type Challenge: Steel!';



exports.water = '/tour name Type Challenge: Water!\n/tour rules -OU, -UU, -RU, -NU, -PU, -ZU, -NFE, -LC, -Uber, -UUBL, -RUBL, -NUBL, -PUBL, -NFE, -LC Uber, -Protean, -Rotom-Wash, +Alomomola, +Araquanid, +Azumarill, +Barbaracle, +Barboach, +Basculin, +Bibarel, +Binacle, +Blastoise, +Blastoise-Mega, +Brionne, +Bruxish, +Buizel, +Carracosta, +Carvanha, +Chinchou, +Clamperl, +Clauncher, +Clawitzer, +Cloyster, +Corphish, +Corsola, +Crawdaunt, +Croconaw, +Dewgong, +Dewott, +Dewpider, +Ducklett, +Empoleon, +Feebas, +Feraligatr, +Finneon, +Floatzel, +Frillish, +Froakie, +Frogadier, +Gastrodon, +Goldeen, +Golduck, +Golisopod, +Gorebyss, +Greninja, +Gyarados, +Gyarados-Mega, +Horsea, +Huntail, +Jellicent, +Kabuto, +Kabutops, +Keldeo, +Kingdra, +Kingler, +Krabby, +Lanturn, +Lapras, +Lombre, +Lotad, +Ludicolo, +Lumineon, +Luvdisc, +Magikarp, +Manaphy, +Mantine, +Mantyke, +Mareanie, +Marill, +Marshtomp, +Milotic, +Mudkip, +Octillery, +Omanyte, +Omastar, +Oshawott, +Palpitoad, +Panpour, +Pelipper, +Phione, +Piplup, +Politoed, +Poliwag, +Poliwhirl, +Poliwrath, +Popplio, +Primarina, +Prinplup, +Psyduck, +Pyukumuku, +Quagsire, +Qwilfish, +Relicanth, +Remoraid, +Samurott, +Seadra, +Seaking, +Sealeo, +Seel, +Seismitoad, +Sharpedo, +Sharpedo-Mega, +Shellder, +Shellos, +Silvally-Water, +Simipour, +Skrelp, +Slowbro, +Slowbro-Mega, +Slowking, +Slowpoke, +Spheal, +Squirtle, +Starmie, +Staryu, +Suicune, +Surskit, +Swampert, +Swampert-Mega, +Swanna, +Tapu Fini, +Tentacool, +Tentacruel, +Tirtouga, +Totodile, +Toxapex, +Tympole, +Vaporeon, +Volcanion, +Wailmer, +Wailord, +Walrein, +Wartortle, +Whiscash, +Wimpod, +Wingull, +Wishiwashi, +Wooper\n/wall Type Challenge: Water!';